services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mdpdefou
      POSTGRES_DB: jardins_cocagne
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d jardins_cocagne"]  # Correction ici
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  nextjs:
    build:
      context: ./my-app  # Spécifiez le chemin vers le répertoire contenant Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - db

networks:
  mynetwork:
    driver: bridge
