name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Docker Compose Down
      run: docker-compose down -v

    - name: Docker Compose Up and Build
      run: docker-compose up --build -d

    - name: Display Docker logs
      run: docker-compose logs

    - name: Wait for services to be healthy
      run: |
        while ! docker-compose ps | grep "healthy"; do
          echo "Waiting for services to be healthy..."
          sleep 10
        done

    - name: Wait for web service to be ready
      run: |
        while ! curl -s http://localhost:3000 > /dev/null; do
          echo "Waiting for web service to be ready..."
          sleep 5
        done

    - name: Run API tests
      run: |
        curl -f http://localhost:3000/api/tournees/index || exit 1
        echo "API test passed!"

    - name: Docker Compose Down
      run: docker-compose down -v

    - name: Clean up Docker images
      run: docker image prune -f